<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>365新鲜事</title>
    <link rel="stylesheet" href="/statics/css/common.css">
    <!--[if lt IE 9]>
    <script src="/statics/js/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
    <div class="header-load"></div>
    <div class="main clearfix">
        <section class="news-wrap">
            <div class="news-banner">
                <ul class="news-carousel">
                    <li class="news-carousel-item current"><a href="#" title="365旅途黑板报"><img src="/statics/images/news_img_banner.jpg" width="766" height="261" alt="365旅途黑板报"></a></li>
                    <li class="news-carousel-item"><a href="#" title="365旅途黑板报"><img src="/statics/images/news_img_banner.jpg" width="766" height="261" alt="365旅途黑板报"></a></li>
                    <li class="news-carousel-item"><a href="#" title="365旅途黑板报"><img src="/statics/images/news_img_banner.jpg" width="766" height="261" alt="365旅途黑板报"></a></li>
                    <li class="news-carousel-item"><a href="#" title="365旅途黑板报"><img src="/statics/images/news_img_banner.jpg" width="766" height="261" alt="365旅途黑板报"></a></li>
                </ul>
                <ul class="news-carousel-control">
                    <li class="news-carousel-control-item current"><a href="#"></a></li>
                    <li class="news-carousel-control-item"><a href="#"></a></li>
                    <li class="news-carousel-control-item"><a href="#"></a></li>
                    <li class="news-carousel-control-item"><a href="#"></a></li>
                </ul>
            </div>
            <div class="news-article">
                {{foreach from=$diary_list item=diary}}
                <article class="clearfix">
                    <img class="article-image" src="{{$diary.thumbnail}}" width="320" height="210" alt="{{$diary.pic_desc}}">
                    <div class="article-wrap">
                        <h2 class="article-title"><a href="/diary/detail/diary_id/{{$diary.diary_id}}" title="{{$diary.title}}">{{$diary.title}}</a></h2>
                        <a class="article-author" href="/home/index/p/{{$diary.user_id}}" title="fond">fond</a><span class="article-from">发表于</span><span class="article-time">{{$diary.update_time|date_format:"%Y-%m-%d %H:%M"}}</span><a class="article-type" href="/news/index/type/{{$diary.type}}">[{{$diary_type_id_to_name[$diary['type']]}}]</a>
                        <p class="article-text">{{$diary.content}}</p>
                    </div>
                </article>
                {{/foreach}}
                <div class="paging-load"></div>
            </div>
        </section>
        <section class="news-aside">
            <aside class="big-logo-wrap">
                <img class="big-logo" src="/statics/images/news_img_biglogo.png" width="137" height="107" alt="365-logo">
                <h1>
                    <div class="big-title"><em class="big-365">365</em><strong>每天记</strong></div>
                    <strong class="big-sub-title">新鲜事</strong>
                </h1>
            </aside>
            <aside class="news-about">
                <h2 class="news-about-title">关于365</h2>
                <p>365是个“每日一片”的网络联盟，通过每天一张的照片，记录分享生活</p>
                <p>我们的口号——请看我漂亮的坚持！</p>
                <p class="news-about-tips">这是个温暖的小集体，各位玩得开心点 :)</p>
                <p class="news-about-know-wrap"><a class="news-know-about clearword" href="/about" title="了解365">了解365</a><a class="news-leave-a-message clearword" href="mailto:i365day@qq.com" title="给我们留言">给我们留言</a></p>
                <p><a class="news-subscribe clearword" href="#" title="订阅365新鲜事">订阅365新鲜事</a></p>
                <ul class="news-about-list">
                    <li class="news-about-item"><a href="/news/index/type/1" title="365周报">365周报</a></li>
                    <li class="new-about-sep"></li>
                    <li class="news-about-item"><a href="/news/index/type/2" title="365线下聚会">365线下聚会</a></li>
                    <li class="new-about-sep"></li>
                    <li class="news-about-item"><a href="/news/index/type/3" title="365黑板报">365黑板报</a></li>
                    <li class="new-about-sep"></li>
                    <li class="news-about-item"><a href="/news/index/type/4" title="365明星同学">365明星同学</a></li>
                    <li class="new-about-sep"></li>
                    <li class="news-about-item"><a href="/news/index/type/5" title="其他">其他</a></li>
                </ul>
            </aside>
            <aside class="news-search">
                <form action="/news/index">
                    <input type="text" name="kw" value="{{$kw|escape}}" placeholder="搜索新鲜事">
                    <button class="news-search-submit clearword" type="submit" title="搜索">搜索</button>
                </form>
            </aside>
            <aside class="all-hot">
                <h2 class="all-hot-title">全站最热</h2>
                <div class="like-load"></div>
            </aside>
        </section>
    </div>
    <div class="footer-load"></div>
    <script src="/statics/js/jquery-1.10.1.min.js"></script>
    <script src="/statics/js/temp-ajax-load.js"></script>
    <script src="/statics/js/common.js"></script>
    <script src="/statics/js/news.js"></script>
</body>
</html>