<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>百望山秋游--365每天记</title>
    <link rel="stylesheet" href="/statics/css/common.css">
    <!--[if lt IE 9]>
    <script src="/statics/js/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
    <div class="header-load"></div>
    <div class="main clearfix">
        <section class="article-detail">
            <article class="article-content-wrap">
                <div class="article-title-wrap">
                    <div class="note-date-label">
                        <strong class="note-date-text">DAY</strong>
                        <em class="note-date-days">212</em>
                    </div>
                    <div class="article-title-detail">
                        <h1 class="article-title">{{$diary.title}}</h1>
                        <div class="article-info">
                            <a href="#" class="article-author" title="{{$user.nick_name}}">{{$user.nick_name}}</a>
                            <span class="article-report-from">发表于</span>
                            <time class="article-time">{{$diary.create_time|date_format:"%Y-%m-%d %H:%M:%S"}}</time>
                        </div>
                    </div>
                </div>
                <div class="article-content">
                    <img src="{{$diary.pic}}" alt="{{$diary.pic_desc}}" class="article-img">
                    <p>{{$diary.content}}</p>
                    <div class="article-label-wrap">
                        
                        {{foreach from = $diary.tags item=tag}}
                            <a href="#" class="article-label" title="{{$tag}}">#{{$tag}}</a>
                        {{/foreach}}
                    </div>
                    <a href="#" class="article-icon-zan clearword" title="赞一个">赞一个</a>
                    <a href="#" class="article-icon-other clearword disable" title="分享">分享</a>
                </div>
            </article>
            <div class="article-leave-message">
                <h2 class="article-message-title">评论</h2>
                <textarea class="comment-text" name="" id="" placeholder="写评论吧"></textarea>
                <div class="comment-btn-wrap">
                    <button class="comment-btn" type="button" title="评论">评论</button>
                </div>
                <div class="comment-load"></div>
            </div>
        </section>
        <section class="article-aside">
            <aside class="article-author-info">
                <div class="clearfix">
                    <img src="/statics/images/home_img_head.jpg" alt="头像" width="90" height="90" class="head-sculpture">
                    <a class="username" href="myhome.html" title="{{$user.nick_name}}">{{$user.nick_name}}</a>
                    <p class="detail-days">123个日子</p>
                    <p class="user-info-guanzhu">
                        <a href="#" class="guanzhu" title="关注他">关注他</a>
                        <a href="#" class="quxiao-guanzhu hide" title="取消关注">取消关注</a>
                    </p>
                </div>
                <p class="article-user-description">{{$user.intro}}</p>
                <p class="usercity">{{$user.city}}</p><p class="device">使用{{$user.camera_brand}} {{$user.camera_model}}</p>
            </aside>
            <aside class="last-year">
                <h2 class="all-hot-title">去年今日</h2>
                <div class="like-load"></div>
            </aside>
            <aside class="last-prev-year">
                <h2 class="all-hot-title">前年今日</h2>
                <div class="like-load"></div>
            </aside>
        </section>
    </div>
    <div class="footer-load"></div>
    <script src="/statics/js/jquery-1.10.1.min.js"></script>
    <script src="/statics/js/temp-ajax-load.js"></script>
    <script src="/statics/js/common.js"></script>
</body>
</html>