<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>发布新日记--365每天记</title>
    <link rel="stylesheet" href="/statics/css/common.css">
    <!--[if lt IE 9]>
    <script src="/statics/js/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
    <div class="header-load"></div>
    <div class="main">
        <form action="/diary/doedit" method="post" enctype="multipart/form-data">
            <h1 class="main-title-icon">发布新日记</h1>
            <div class="note-content line">
                <div class="note-form">
                    <div class="note-img-wrap clearfix">
                        <div class="note-date-wrap clearfix">
                            <div class="note-date-label">
                                <strong class="note-date-text">DAY</strong>
                                <em class="note-date-days">{{$duration}}</em>
                            </div>
                            <time class="note-date">{{$date_ts|date_format:"%Y.%m.%d"}}</time>
                        </div>
                        <div class="note-img-window">
                            <div class="note-img-tips">
                                <i class="note-img-icon"></i>
                                <p>目前仅支持jpg、png格式</p>
                            </div>
                            <img class="note-img"  src="{{$diary.pic}}" alt="" style="height: 288px; display: inline; width: 288px;">
                            <input type="file" class="note-img-upload" name="pic" title="点击选择文件">
                        </div>
                        <input type="text" class="note-img-description" name="pic_desc" placeholder="图片说明...(可选)" value="{{$diary.pic_desc}}">
                    </div>
                    <div class="note-text-wrap">
                        <input type="text" class="note-text-title" name="title" placeholder="填写标题...(可选)" value="{{$diary.title}}">
                        <textarea class="note-text" name="content">{{$diary.content}}</textarea>
                        <ul class="extendinputwrap">
                            {{foreach from = $diary.tags item=tag}}
                               <li class="extenditem">
                                <label>{{$tag}}</label>
                                <a class="extendclose" href="#" title="移除此项"></a>
                                <input name="tags[]" value="{{$tag}}" style="display:none;">
                                </li>
                            {{/foreach}}
                            <li class="otheritem">
                                <input id="city" name="tags[]" type="text" placeholder="#标签" maxlength="20" />
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="note-btn-wrap">
                    <button class="note-send clearword" type="submit" title="写好了,发布">写好了,发布</button>
                    <label><input type="checkbox" class="note-secret" name="private" {{if $diary.visibility}}checked{{/if}}/>仅自己可见</label>
                    <div class="note-sync-wrap">
                        <span class="note-sync-text">同步到:</span>
                        <a href="#" title="sina" class="login-sina">新浪登录</a>
                        <a href="#" title="dou" class="login-dou">豆瓣登录</a>
                    </div>
                </div>
            </div>
            <input type ="hidden" name ='date' value ="{{$diary.date}}"/>
            <input type ="hidden" name ='date_ts' value ="{{$diary.date_ts}}"/>
            <input type ="hidden" name ='diary_id' value ="{{$diary.diary_id}}"/>
            <input type ="hidden" name ='diary_ext_id' value ="{{$diary.diary_ext_id}}"/>
        </form>
    </div>
    <div class="footer-load"></div>
    <script src="/statics/js/jquery-1.10.1.min.js"></script>
    <script src="/statics/js/temp-ajax-load.js"></script>
    <script src="/statics/js/common.js"></script>
</body>
</html>