<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>关于我们--365每天记</title>
    <link rel="stylesheet" href="/statics/css/common.css">
    <!--[if lt IE 9]>
    <script src="/statics/js/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
    <div class="header-load"></div>
    <div class="container">
        <div class="content clearfix">
            <div id="main">
                <h1 class="aboutus-title">关于365</h1>
                <div class="main-content line">
                <div class="aboutus-content">
                    <p>
                    你经常对着书店里的绵绵不绝的封面发呆吗？或者头晕脑涨地从音像店的琳琅满目中逃出？宽带下载和网上购物降临之后，即使在最小的城镇，你的选择也在每天成百上千地增加。这其中一定有你会喜爱的东西，但十有八九它们会在不知不觉中和你擦肩而过。媒体让老少咸宜的大片无处不在，对只适合一群人的东西却显得力不从心。而且，萝卜青菜，各有所爱，不管电视的娱乐编辑和报纸的书评作家多么公正和勤勉，他们的帮助都不可能对所有人同样有效。
                    </p>
                    <p>
                    豆瓣的发起者发现，对多数人做选择最有效的帮助其实来自亲友和同事。随意的一两句推荐，不但传递了他们自己真实的感受，也包含了对你口味的判断和随之而行的筛选。他们不会向单身汉推荐育儿大全，也不会给老妈带回赤裸特工。遗憾的是，你我所有的亲友加起来，听过看过的仍然有限。而且，口味最类似的人却往往是陌路。
                    </p>
                </div>
                    <div class="attention">
                        <span>关注我们：</span>
                        <a class="aboutus-sina" href="http://www.weibo.com/" target="_blank">@365day</a>
                        <a class="aboutus-dou" href="http://www.douban.com/" target="_blank">豆瓣小站</a>
                        <p>合作邮件请发送： 365day@i365day.com</p>
                    </div>
                </div>
            </div>
            <div id="about-sidebar" class="line">
                <div class="sidebar-content">
                    <ul class="sidebartop line">
                        <li><a href="maito:i365day@qq.com" title="给我们留言" class="aboutus-email">给我们留言</a></li>
                        <li><a href="/news" title="365新鲜事" class="aboutus-new">365新鲜事</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="footer-load"></div>
    </div>
    
    <script src="/statics/js/jquery-1.10.1.min.js"></script>
    <script src="/statics/js/temp-ajax-load.js"></script>
    <script src="/statics/js/common.js"></script>
</body>
</html>