<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>小伙伴的全部新鲜事--365每天记</title>
    <link rel="stylesheet" href="/statics/css/common.css">
    <!--[if lt IE 9]>
    <script src="/statics/js/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
    <div class="header-load"></div>
    <div id="friend-content" class="clearfix">
        <div class="white-bg"></div>
        <div id="main" class="friend">
            <h1>全部动态</h1>
            <div class="main-content line">

                {{foreach from = $feeds item=feed}}
                    {{assign var="feed_content" value=$feed.content|json_decode:true}}
                    {{if $feed.type == 3}}
                    <div class="fried-state">
                        <div class="make-friend">
                            <a href="/home/index/p/{{$feed.user_id}}" class="friend-name" title="{{$feed.user_name}}">{{$feed.user_name}}</a>关注了<a href="/home/index/p/{{$feed_content.followId}}"" class="friend-name" title="{{$feed_content.followNickName}}">{{$feed_content.followNickName}}</a>
                        </div>
                    </div>
                    {{/if}}

                    {{if $feed.type == 1}}
                    <div class="friend-state">
                        <a href="#" title="" class="friend-pic"><img src="/statics/images/friend-pic.gif"></a>
                        <div class="record">
                            <a href="/home/index/p/{{$feed.user_id}}" class="friend-name" title="{{$feed.user_name}}">{{$feed.user_name}}</a>记录了{{$feed_content.title}}
                            <div class="record-content clearfix">
                                <div class="pic">
                                    <a href="/home/index/p/{{$feed.user_id}}" title="{{$feed.user_name}}"><img src="/statics/images/friend.gif" width="100" height="100"/></a>
                                </div>
                                <a href="/diary/detail/diary_id/{{$feed_content.diary_id}}" class="info">
                                    <h3>{{$feed_content.title}}</h3>
                                    <p>{{$feed_content.content}}</p>
                                </a>
                            </div>
                            <div class="publish-date">{{$feed.formatted_time}}</div>
                        </div>
                    </div>
                    {{/if}}

                    {{if $feed.type == 2}}
                    <div class="like-friend">
                        <a href="#" class="friend-name" title="入江直树">{{$feed.user_name}}</a>喜欢了<a href="#" class="friend-name" title="相原琴子">相原琴子</a>的日记
                        <div class="like-content clearfix">
                            <div class="pic">
                                <a href="#" title=""><img src="/statics/images/like.gif" width="70" height="70"/></a>
                            </div>
                            <a href="#" class="info">
                                <h3>{{$feed_content.title}}</h3>
                                <p>{{$feed_content.content}}</p>
                            </a>
                        </div>
                        <div class="publish-date">{{$feed.formatted_time}}</div>
                    </div>
                    {{/if}}
                {{/foreach}}

<!--                <div class="paging-load"></div>-->
            </div>
        </div>
        <div id="sidebar">
            <h2>我的关注 <a href="interest.html" class="myfocus-num">78</a></h2>
            <div class="sidebar-content">
                <div class="myfocus clearfix">
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">ezuojuzhiwen</span>
                    </a>
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">ezuojuzhiwen</span>
                    </a>
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">who</span>
                    </a>
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">ezuojuzhiwen</span>
                    </a>
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">EXO</span>
                    </a>
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">who</span>
                    </a>
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">一吻定情</span>
                    </a>
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">入江裕树</span>
                    </a>
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">who</span>
                    </a>
                </div>
            </div>
            <aside class="all-hot">
                <h2 class="all-hot-title">全站最热</h2>
                <div class="like-load"></div>
            </aside>
        </div>
    </div>
    <div class="footer-load"></div>
    <script src="/statics/js/jquery-1.10.1.min.js"></script>
    <script src="/statics/js/temp-ajax-load.js"></script>
    <script src="/statics/js/common.js"></script>
</body>
</html>