<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>小伙伴的全部新鲜事--365每天记</title>
    <link rel="stylesheet" href="/statics/css/common.css">
    <!--[if lt IE 9]>
    <script src="/statics/js/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
    <div class="header-load"></div>
    <div id="friend-content" class="clearfix">
        <div class="white-bg"></div>
        <div id="main" class="friend">
            <h1>全部动态</h1>
            <div class="main-content line">
                <div class="friend-state">
                    <a href="#" title="" class="friend-pic"><img src="/statics/images/friend-pic.gif"></a>
                    <div class="record">
                        <a href="#" class="friend-name" title="入江直树">入江直树</a>记录了第308天
                        <div class="record-content clearfix">
                            <div class="pic">
                                <a href="#" title=""><img src="/statics/images/friend.gif" width="100" height="100"/></a>
                            </div>
                            <a href="#" class="info">
                                <h3>薰豆梨肉玛德莲蛋糕</h3>
                                <p>之前保证过出一个简单易行的食谱，今天就来向大家介绍这款薰豆梨肉玛德莲蛋糕。
玛德莲蛋糕（madeleine，petite madeleine）是一种传统的贝壳形状的小蛋糕，来自于法国东北部洛林大区的两个市镇科梅尔西和Liverdun。</p>
                            </a>
                        </div>
                        <div class="publish-date">23:22</div>
                    </div>
                    <div class="like-friend">
                        <a href="#" class="friend-name" title="入江直树">入江直树</a>喜欢了<a href="#" class="friend-name" title="相原琴子">相原琴子</a>的日记
                        <div class="like-content clearfix">
                            <div class="pic">
                                <a href="#" title=""><img src="/statics/images/like.gif" width="70" height="70"/></a>
                            </div>
                            <a href="#" class="info">
                                <h3>薰豆梨肉玛德莲蛋糕</h3>
                                <p>之前保证过出一个简单易行的食谱，今天就来向大家介绍这款薰豆梨肉玛德莲蛋糕。
梅尔西和Liverdun。</p>
                            </a>
                        </div>
                        <div class="publish-date">昨天04:22</div>
                    </div>
                </div>
                <div class="friend-state">
                    <a href="#" title="" class="friend-pic"><img src="/statics/images/friend-pic.gif"></a>
                    <div class="record">
                        <a href="#" class="friend-name" title="入江直树">入江直树</a>记录了他第一次遇到相原琴子的第一天
                        <div class="record-content clearfix">
                            <div class="pic">
                                <a href="#" title=""><img src="/statics/images/friend.gif" width="100" height="100"/></a>
                            </div>
                            <a href="#" class="info">
                                <h3>薰豆梨肉玛德莲蛋糕</h3>
                                <p>之前保证过出一个简单易行的食谱，今天就来向大家介绍这款薰豆梨肉玛德莲蛋糕。
玛德莲蛋糕（madeleine，petite madeleine）是一种传统的贝壳形状的小蛋糕，来自于法国东北部洛林大区的两个市镇科梅尔西和Liverdun。</p>
                            </a>
                        </div>
                        <div class="publish-date">23:22</div>
                    </div>
                    <div class="make-friend">
                        <a href="#" class="friend-name" title="入江直树">入江直树</a>和<a href="#" class="friend-name" title="相原琴子">相原琴子</a>成为了朋友
                    </div>
                    <div class="make-friend">
                        <a href="#" class="friend-name" title="入江直树">入江直树</a>和<a href="#" class="friend-name" title="相原琴子">相原琴子</a>成为了朋友
                    </div>
                </div>
                <div class="friend-state">
                    <a href="#" title="" class="friend-pic"><img src="/statics/images/friend-pic.gif"></a>
                    <div class="record">
                        <a href="#" class="friend-name" title="入江直树">入江直树</a>记录了第308天
                        <div class="record-content clearfix">
                            <div class="pic">
                                <a href="#" title=""><img src="/statics/images/friend.gif" width="100" height="100"/></a>
                            </div>
                            <a href="#" class="info">
                                <h3>薰豆梨肉玛德莲蛋糕</h3>
                                <p>之前保证过出一个简单易行的食谱，今天就来向大家介绍这款薰豆梨肉玛德莲蛋糕。
玛德莲蛋糕（madeleine，petite madeleine）是一种传统的贝壳形状的小蛋糕，来自于法国东北部洛林大区的两个市镇科梅尔西和Liverdun。</p>
                            </a>
                        </div>
                        <div class="publish-date">23:22</div>
                    </div>
                    <div class="record">
                        <a href="#" class="friend-name" title="入江直树">入江直树</a>记录了第308天
                        <div class="record-content clearfix">
                            <div class="pic">
                                <a href="#" title=""><img src="/statics/images/friend.gif" width="100" height="100"/></a>
                            </div>
                            <a href="#" class="info">
                                <h3>薰豆梨肉玛德莲蛋糕</h3>
                                <p>之前保证过出一个简单易行的食谱，今天就来向大家介绍这款薰豆梨肉玛德莲蛋糕。
玛德莲蛋糕（madeleine，petite madeleine）是一种传统的贝壳形状的小蛋糕，来自于法国东北部洛林大区的两个市镇科梅尔西和Liverdun。</p>
                            </a>
                        </div>
                        <div class="publish-date">23:22</div>
                    </div>
                </div>
                <div class="friend-state">
                    <a href="#" title="" class="friend-pic"><img src="/statics/images/friend-pic.gif"></a>
                    <div class="record">
                        <a href="#" class="friend-name" title="入江直树">入江直树</a>记录了他第一次遇到相原琴子的第一天
                        <div class="record-content clearfix">
                            <div class="pic">
                                <a href="#" title=""><img src="/statics/images/friend.gif" width="100" height="100"/></a>
                            </div>
                            <a href="#" class="info">
                                <h3>薰豆梨肉玛德莲蛋糕</h3>
                                <p>之前保证过出一个简单易行的食谱，今天就来向大家介绍这款薰豆梨肉玛德莲蛋糕。
玛德莲蛋糕（madeleine，petite madeleine）是一种传统的贝壳形状的小蛋糕，来自于法国东北部洛林大区的两个市镇科梅尔西和Liverdun。</p>
                            </a>
                        </div>
                        <div class="publish-date">23:22</div>
                    </div>
                    <div class="make-friend">
                        <a href="#" class="friend-name" title="入江直树">入江直树</a>和<a href="#" class="friend-name" title="相原琴子">相原琴子</a>成为了朋友
                    </div>
                    <div class="make-friend">
                        <a href="#" class="friend-name" title="入江直树">入江直树</a>和<a href="#" class="friend-name" title="相原琴子">相原琴子</a>成为了朋友
                    </div>
                </div>
                <div class="friend-state">
                    <a href="#" title="" class="friend-pic"><img src="/statics/images/friend-pic.gif"></a>
                    <div class="record">
                        <a href="#" class="friend-name" title="入江直树">入江直树</a>记录了他第一次遇到相原琴子的第一天
                        <div class="record-content clearfix">
                            <div class="pic">
                                <a href="#" title=""><img src="/statics/images/friend.gif" width="100" height="100"/></a>
                            </div>
                            <a href="#" class="info">
                                <h3>薰豆梨肉玛德莲蛋糕</h3>
                                <p>之前保证过出一个简单易行的食谱，今天就来向大家介绍这款薰豆梨肉玛德莲蛋糕。
玛德莲蛋糕（madeleine，petite madeleine）是一种传统的贝壳形状的小蛋糕，来自于法国东北部洛林大区的两个市镇科梅尔西和Liverdun。</p>
                            </a>
                        </div>
                        <div class="publish-date">23:22</div>
                    </div>
                    <div class="make-friend">
                        <a href="#" class="friend-name" title="入江直树">入江直树</a>和<a href="#" class="friend-name" title="相原琴子">相原琴子</a>成为了朋友
                    </div>
                    <div class="make-friend">
                        <a href="#" class="friend-name" title="入江直树">入江直树</a>和<a href="#" class="friend-name" title="相原琴子">相原琴子</a>成为了朋友
                    </div>
                </div>
                <div class="paging-load"></div>
            </div>
        </div>
        <div id="sidebar">
            <h2>我的关注 <a href="interest.html" class="myfocus-num">78</a></h2>
            <div class="sidebar-content">
                <div class="myfocus clearfix">
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">ezuojuzhiwen</span>
                    </a>
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">ezuojuzhiwen</span>
                    </a>
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">who</span>
                    </a>
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">ezuojuzhiwen</span>
                    </a>
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">EXO</span>
                    </a>
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">who</span>
                    </a>
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">一吻定情</span>
                    </a>
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">入江裕树</span>
                    </a>
                    <a href="#" title="">
                        <img src="/statics/images/friend-pic.gif" width="50" height="50">
                        <span class="myfocus-name">who</span>
                    </a>
                </div>
            </div>
            <aside class="all-hot">
                <h2 class="all-hot-title">全站最热</h2>
                <div class="like-load"></div>
            </aside>
        </div>
    </div>
    <div class="footer-load"></div>
    <script src="/statics/js/jquery-1.10.1.min.js"></script>
    <script src="/statics/js/temp-ajax-load.js"></script>
    <script src="/statics/js/common.js"></script>
</body>
</html>