<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>留言板--365每天记</title>
        <link rel="stylesheet" href="/statics/css/common.css">
        <!--[if lt IE 9]>
        <script src="/statics/js/html5shiv.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="header-load"></div>
        <div class="main">
            <div class="home-load"></div>
            <section class="home-note-wrap">
                <div class="home-nav-wrap clearfix">
                    <ul class="home-tab-wrap clearfix">
                        <li class="home-tab-item"><a href="/home" title="我的365">我的365</a></li>
                        <li class="home-tab-item"><a href="/like" title="喜欢">喜欢</a></li>
                        <li class="home-tab-item current"><a href="/msg" title="留言板">留言板</a></li>
                    </ul>
                    <a class="write-now clearword" href="newnote.html" title="记录今天">记录今天</a>
                </div>
            </section>
            <section class="leave-message-wrap">
                <form action="/leavingMsg/docreate" method="post">
                    <input type="hidden" name="follow_id" id="follow_id"/>
                    <input type="hidden" name="host_id" value="{{$user.user_id}}">
                    <div class="leave-message">
                        <textarea class="comment-text" name="content" id="" placeholder="写留言吧"></textarea>
                        <div class="comment-btn-wrap">
                            <button class="comment-btn" type="submit" title="留言">留 言</button>
                        </div>
                        <div class="leavingmsg-load"></div>
                        <div class="paging-load"></div>
                    </div>
                </form>
            </section>
        </div>
        <div class="footer-load"></div>
        <script src="/statics/js/jquery-1.10.1.min.js"></script>
        <script src="/statics/js/temp-ajax-load.js"></script>
        <script src="/statics/js/common.js"></script>
    </body>
</html>