<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的关注--365每天记</title>
    <link rel="stylesheet" href="/statics/css/common.css">
    <!--[if lt IE 9]>
    <script src="/statics/js/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
    <div class="header-load"></div>
    <div class="main">
        <div class="home-load"></div>
        <section class="home-note-wrap">
            <div class="home-nav-wrap clearfix">
                <ul class="home-tab-wrap clearfix">
                    <li class="home-tab-item"><a href="myhome.html" title="我的365">我的365</a></li>
                    <li class="home-tab-item"><a href="like.html" title="喜欢">喜欢</a></li>
                    <li class="home-tab-item"><a href="message.html" title="留言板">留言板</a></li>
                </ul>
                <a class="write-now clearword" href="newnote.html" title="记录今天">记录今天</a>
            </div>
        </section>
        <section class="fans">
            <div class="fans-title-wrap clearfix line">
                <div class="fans-title">
                    <a href="interest.html" class="inline-block fans-myinterest current">我的关注<em>32</em></a>
                    <a href="fans.html" class="inline-block fans-myfans">我的粉丝<em>298</em></a>
                </div>
                <div class="news-search">
                    <form>
                        <input type="text" placeholder="在列表中搜索朋友">
                        <button class="news-search-submit clearword" type="submit" title="搜索">搜索</button>
                    </form>
                </div>
            </div>
            <ul class="fans-list clearfix">
                <li class="fans-item">
                    <a href="#" class="fans-head" title="晓晨晓晨"><img src="/statics/images/fans_img_head.jpg" alt=""></a>
                    <a href="#" class="fans-name" title="晓晨晓晨">晓晨晓晨</a>
                    <a href="#" class="cancel-fans" title="取消关注">取消关注</a>
                    <div class="fans-detail">
                        <a href="" class="fans-day" title="查看他的日记">102个日子</a>
                        <a href="#" class="fans-fans" title="查看他的粉丝">1999个粉丝</a>
                    </div>
                </li>
                <li class="fans-item">
                    <a href="#" class="fans-head" title="晓晨晓晨"><img src="/statics/images/fans_img_head.jpg" alt=""></a>
                    <a href="#" class="fans-name" title="晓晨晓晨">晓晨晓晨</a>
                    <a href="#" class="cancel-fans" title="取消关注">取消关注</a>
                    <div class="fans-detail">
                        <a href="" class="fans-day" title="查看他的日记">102个日子</a>
                        <a href="#" class="fans-fans" title="查看他的粉丝">1999个粉丝</a>
                    </div>
                </li>
                <li class="fans-item">
                    <a href="#" class="fans-head" title="晓晨晓晨"><img src="/statics/images/fans_img_head.jpg" alt=""></a>
                    <a href="#" class="fans-name" title="晓晨晓晨">晓晨晓晨</a>
                    <a href="#" class="cancel-fans" title="取消关注">取消关注</a>
                    <div class="fans-detail">
                        <a href="" class="fans-day" title="查看他的日记">102个日子</a>
                        <a href="#" class="fans-fans" title="查看他的粉丝">1999个粉丝</a>
                    </div>
                </li>
                <li class="fans-item">
                    <a href="#" class="fans-head" title="晓晨晓晨"><img src="/statics/images/fans_img_head.jpg" alt=""></a>
                    <a href="#" class="fans-name" title="晓晨晓晨">晓晨晓晨</a>
                    <a href="#" class="cancel-fans" title="取消关注">取消关注</a>
                    <div class="fans-detail">
                        <a href="" class="fans-day" title="查看他的日记">102个日子</a>
                        <a href="#" class="fans-fans" title="查看他的粉丝">1999个粉丝</a>
                    </div>
                </li>
                <li class="fans-item">
                    <a href="#" class="fans-head" title="晓晨晓晨"><img src="/statics/images/fans_img_head.jpg" alt=""></a>
                    <a href="#" class="fans-name" title="晓晨晓晨">晓晨晓晨</a>
                    <a href="#" class="cancel-fans" title="取消关注">取消关注</a>
                    <div class="fans-detail">
                        <a href="" class="fans-day" title="查看他的日记">102个日子</a>
                        <a href="#" class="fans-fans" title="查看他的粉丝">1999个粉丝</a>
                    </div>
                </li>
                <li class="fans-item">
                    <a href="#" class="fans-head" title="晓晨晓晨"><img src="/statics/images/fans_img_head.jpg" alt=""></a>
                    <a href="#" class="fans-name" title="晓晨晓晨">晓晨晓晨</a>
                    <a href="#" class="cancel-fans" title="取消关注">取消关注</a>
                    <div class="fans-detail">
                        <a href="" class="fans-day" title="查看他的日记">102个日子</a>
                        <a href="#" class="fans-fans" title="查看他的粉丝">1999个粉丝</a>
                    </div>
                </li>
            </ul>
            <div class="paging-load"></div>
        </section>
    </div>
    <div class="footer-load"></div>
    <script src="/statics/js/jquery-1.10.1.min.js"></script>
    <script src="/statics/js/temp-ajax-load.js"></script>
    <script src="/statics/js/common.js"></script>
</body>
</html>