<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="/statics/css/common.css">
    <!--[if lt IE 9]>
    <script src="/statics/js/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
    <ul class="comment-detail">
        {{foreach from=$comment_list item=comment}}
            <li class="comment-item">
                <img class="comment-head" src="/statics/images/message_img_smallhead.jpg" alt="头像">
                <div class="comment-main">
                    {{if $comment.follow_id != 0}}
                        <div class="reply-quote">
                            <span>{{$comment_associate[$comment['follow_id']]['content']}}</span><a href="#" class="reply-to-author" title="{{$comment.vistor_name}}">{{$comment.vistor_name}}</a>
                        </div>
                    {{/if}}
                    <p class="comment-content"><a class="article-author" href="#" title="{{$comment.vistor_name}}">{{$comment.vistor_name}}:</a>{{$comment.content}}</p>
                    <p class="comment-other">
                        <time class="article-time">{{$comment.create_time|date_format:"%Y年%m月%d日 %H:%M"}}</time><a href="" class="reply" title="回复" alt ="{{$comment.comment_id}}">回复</a><a href="#" class="delete" title="删除" alt ="{{$comment.comment_id}}">删除</a>
                    </p>
                </div>
            </li>
        {{/foreach}}
    </ul>
</body>
</html>