<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="/statics/css/common.css">
    <!--[if lt IE 9]>
    <script src="/statics/js/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
    <ul class="comment-detail">
        {{foreach from=$comment_list item=comment}}
            <li class="comment-item">
                <img class="comment-head" src="/statics/images/message_img_smallhead.jpg" alt="头像">
                <div class="comment-main">
                    <p class="comment-content"><a class="article-author" href="#" title="{{$comment.vistor_name}}">{{$comment.vistor_name}}:</a>{{$comment.content}}</p>
                    <p class="comment-other">
                        <time class="article-time">{{$comment.create_time|date_format:"%Y年%m月%d日 %H:%M"}}</time><a href="" class="reply" title="回复" alt ="{{$comment.comment_id}}">回复</a><a href="#" class="delete" title="删除" alt ="{{$comment.comment_id}}">删除</a>
                    </p>
                </div>
            </li>
        {{/foreach}}
         <li class="comment-item">
            <img class="comment-head" src="/statics/images/message_img_smallhead.jpg" alt="头像">
            <div class="comment-main">
                <div class="reply-quote">
                    <span>让上网更安全，立即下载百度杀毒。让上网更安全，立即下载百度杀毒。让上网更安全，立即下载百度杀毒。让上网更安全，立即下载百度杀毒。让上网更安全，立即下载百度杀毒。</span><a href="#" class="reply-to-author" title="于蓁">于蓁</a>
                </div>
                <p class="comment-content"><a class="article-author" href="#" title="fond">fond:</a>共生在动植物身上的微生物，不只是窃取营养的被动食客。在动植物演化过程中，它们或许发挥着重要作用。<a class="article-author" href="#" title="于蓁">@于蓁</a>共生在动植物身上的微生物。</p>
                <p class="comment-other">
                    <time class="article-time">2012年11月08日 21:09</time><a href="#" class="reply" title="回复">回复</a><a href="#" class="delete" title="删除">删除</a>
                </p>
            </div>
        </li>
    </ul>
</body>
</html>