<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新鲜事--365每天记</title>
    <link rel="stylesheet" href="/statics/css/common.css">
    <!--[if lt IE 9]>
    <script src="/statics/js/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
    <header class="header">
        <div class="header-wrap clearfix">
            <div class="nav clearfix">
                <strong class="logo"><a class="clearword" href="index.html" title="365每天记">365每天记</a></strong>
                <nav>
                    <ul class="nav-wrap clearfix">
                        <li class="nav-item {{if $current_page == 'home' || $current_page == 'like' || $current_page == 'msg'}}current{{/if}}"><a href="/home" title="我的首页">我的首页</a></li>
                        <li class="nav-item {{if $current_page == 'friend'}}current{{/if}}"><a href="/friend" title="小伙伴">小伙伴</a></li>
                        <li class="nav-item {{if $current_page == 'news'}}current{{/if}}"><a href="/news" title="黑板报">黑板报</a></li>
                    </ul>
                </nav>
            </div>
            <div class="login-info clearfix">
                <a class="message-num" href="#" title="" style="display: none;">0</a>
                <div class="info-username clearfix">
                    <a class="info-userlink" href="#" title="meixiaofang">{{$user.nick_name}}</a>
                    <b></b>
                    <ul class="user-menu">
                        <li><a class="menu-item menu-message" href="#" title="查看消息">消息</a></li>
                        <li><a class="menu-item menu-setting" href="/setting" title="修改设置">设置</a></li>
                        <li><a class="menu-item menu-invite" href="/invite" title="邀请朋友">邀请</a></li>
                        <li><a class="menu-item menu-logout" href="#" title="明天见!">退出</a></li>
                    </ul>
                </div>
                <div class="message j-message" id="message-board">
                    <strong class="message-title">消息中心</strong>
                    <ul class="message-wrap" id="message-list">
                    </ul>
                    <!--a href="#" class="message-close clearword j-message-close" id="message-close" title="关闭消息中心">关闭消息中心</a-->
                </div>
            </div>
        </div>
    </header>
    <script src="/statics/js/jquery-1.10.1.min.js"></script>
    <script src="/statics/js/common.js"></script>
</body>
</html>