<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Document</title>
        <link rel="stylesheet" href="/statics/images/common.css">
        <!--[if lt IE 9]>
        <script src="/statics/js/html5shiv.js"></script>
        <![endif]-->
    </head>
    <body>
        <section class="home-info-wrap clearfix">
            <div class="user-info-wrap clearfix">
                <img src="{{$user.head_portrait}}" alt="头像" width="90" height="90" class="head-sculpture">
                <div class="user-info-innerwrap">
                    <h1 class="username">{{$user.nick_name}}</h1>
                    <p class='usercity-wrap'><span class="usercity">{{$user.city}}</span><span class="device">使用{{$user.camera}}</span></p>
                    {{if !$is_self}}
                    <p class="user-info-guanzhu">
                        <a href="#" class="guanzhu" title="关注他" id="add-attention" alt="{{$user.user_id}}" user-name="{{$user.nick_name}}" {{if $is_follow}}style="display: none"{{/if}}>关注他</a>
                        <a href="#" class="quxiao-guanzhu" id="cancel-attention" title="取消关注" alt="{{$user.user_id}}" {{if !$is_follow}}style="display: none"{{/if}}>取消关注</a>
                    </p>
                    {{/if}}
                    <div class="user-info-links">
                        <a class="douban clearword" href="#" title="豆瓣">豆瓣</a>
                        <a class="sina clearword" href="#" title="新浪微博">新浪微博</a></div>
                    <a class="user-info-setting clearword" href="#" title="设置">设置</a>
                </div>
            </div>
            <div class="day-wrap">
                <em class="day-num">{{$diary_days}}</em><span class="day-text">个日子</span>
            </div>
            <div class="user-description-wrap">
                <p>{{$user.intro}}</p>
                <a href="#" class="modify-description clearword" title="修改" alt="{{$user.user_id}}">修改</a>
            </div>
            <div class="user-fans-wrap">
                <p class="user-interest"><a href="/follow{{if !$is_self}}/index/p/{{$user.user_id}}{{/if}}" title="查看关注"><em class="user-interest-num">{{$user.follows}}</em>个关注</a></p>
                <p class="user-fans"><a href="/fans{{if !$is_self}}/index/p/{{$user.user_id}}{{/if}}" title="查看粉丝"><em class="user-fans-num">{{$user.fans}}</em>个粉丝</a></p>
            </div>
        </section>
        <section class="home-info-wrap clearfix">
            <div class="home-nav-wrap clearfix">
                <ul class="home-tab-wrap clearfix">
                    <li class="home-tab-item {{if $current_page == 'home'}}current{{/if}}"><a href="/home{{if !$is_self}}/index/p/{{$current_user_id}}{{/if}}" title="我的365">{{if $is_self}}我{{else}}{{$user.nick_name}}{{/if}}的365</a></li>
                    <li class="home-tab-item {{if $current_page == 'like'}}current{{/if}}"><a href="/like{{if !$is_self}}/index/p/{{$current_user_id}}{{/if}}" title="喜欢">喜欢</a></li>
                    <li class="home-tab-item {{if $current_page == 'msg'}}current{{/if}}"><a href="/msg{{if !$is_self}}/index/p/{{$current_user_id}}{{/if}}" title="留言板">留言板</a></li>
                </ul>
                {{if $is_record_today_show}}<a class="write-now clearword" href="/diary/create" title="记录今天">记录今天</a>{{/if}}
            </div>
        </section>
        <script src="/statics/js/jquery-1.10.1.min.js"></script>
        <script src="/statics/js/common.js"></script>
        <script src="/statics/js/news.js"></script>
    </body>
</html>