<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="/statics/css/common.css">
    <!--[if lt IE 9]>
    <script src="/statics/js/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
    <ul class="leavingmsg-detail">
        {{foreach from=$leaving_msg_list item=msg}}
            <li class="comment-item">
                <img class="comment-head" src="/statics/images/message_img_smallhead.jpg" alt="头像">
                <div class="comment-main">
                    <p class="comment-content"><a class="article-author" href="#" title="{{$msg.vistor_name}}">{{$msg.vistor_name}}:</a>{{$msg.content}}</p>
                    <p class="comment-other">
                        <time class="article-time">{{$msg.create_time|date_format:"%Y年%m月%d日 %H:%M"}}</time><a href="" class="reply" title="回复" alt ="{{$msg.leaving_msg_id}}">回复</a><a href="#" class="delete" title="删除" alt ="{{$msg.leaving_msg_id}}">删除</a>
                    </p>
                </div>
            </li>
        {{/foreach}}
    </ul>
</body>
</html>