<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="/statics/css/common.css">
    <!--[if lt IE 9]>
    <script src="/statics/js/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
    <div class="all-hot-content clearfix">
        <img src="/statics/images/news_img_hottest.jpg" alt="全站最热" width="251" height="251" class="all-hot-image">
        <div class="all-hot-article">
            <h3 class="all-hot-article-title"><a href="detail.html" title="在家煮了砂锅粥">在家煮了砂锅粥</a></h3>
            <a class="article-author" href="myhome.html" title="fond">fond</a><span class="article-time">2012-11-08</span>
        </div>
        <div class="all-hot-evaluate">
            <div>
                <a href="#" class="evaluate-good clearword" title="喜欢">喜欢</a><em>123</em>
            </div>
            <div>
                <a href="#" class="evaluate-weak clearword" title="不喜欢">不喜欢</a><em>4</em>
            </div>
        </div>
    </div>
</body>
</html>