<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <link rel="stylesheet" href="/statics/css/common.css">
</head>
<body>
    <div class="article-paging-box">
        <ul class="article-paging-wrap clearfix">
            <li class="article-paging-item"><a href="#" title="上一页">&lt上一页</a></li>
            <li class="article-paging-item current"><a href="#" title="第1页">1</a></li>
            <li class="article-paging-item"><a href="#" title="第2页">2</a></li>
            <li class="article-paging-item"><a href="#" title="第3页">3</a></li>
            <li class="article-paging-item"><a href="#" title="第4页">4</a></li>
            <li class="article-paging-item">...</li>
            <li class="article-paging-item"><a href="#" title="下一页">下一页&gt</a></li>
        </ul>
    </div>
</body>
</html>