<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>我的关注--365每天记</title>
    <link rel="stylesheet" href="/statics/css/common.css">
    <!--[if lt IE 9]>
    <script src="/statics/js/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
    <div class="header-load"></div>
    <div class="main">
        <div class="home-load"></div>

        <section class="fans">
            <div class="fans-title-wrap clearfix line">
                <div class="fans-title">
                    <a href="/follow{{if !$is_self}}/index/p/{{$userInfo.user_id}}{{/if}}" class="inline-block fans-myinterest current">{{if $is_self}}我{{else}}{{$userInfo.nick_name}}{{/if}}的关注<em>{{$userInfo.follows}}</em></a>
                    <a href="#" class="inline-block fans-myfans">{{if $is_self}}我{{else}}{{$userInfo.nick_name}}{{/if}}的粉丝<em>{{$userInfo.fans}}</em></a>
                </div>
<!--                <div class="news-search">-->
<!--                    <form>-->
<!--                        <input type="text" placeholder="在列表中搜索朋友">-->
<!--                        <button class="news-search-submit clearword" type="submit" title="搜索">搜索</button>-->
<!--                    </form>-->
<!--                </div>-->
            </div>
            <ul class="fans-list clearfix">
                {{foreach from = $fans item=fan}}
                <li class="fans-item">
                    <a href="/home/index/p/{{$fan.user_id}}" class="fans-head" title="{{$fan.nick_name}}"><img src="/statics/images/fans_img_head.jpg" alt=""></a>
                    <a href="/home/index/p/{{$fan.user_id}}" class="fans-name" title="{{$fan.nick_name}}">{{$fan.nick_name}}</a>

                    <a href="#" class="quxiao-guanzhu cancel-attention" id="cancel-attention-{{$fan.user_id}}" title="取消关注" alt="{{$fan.user_id}}" {{if !$fan.is_follow}}style="display: none"{{/if}}>取消关注</a>
                    <a href="#" class="guanzhu add-attention" id="add-attention-{{$fan.user_id}}" title="关注" alt="{{$fan.user_id}}" user-name="{{$fan.nick_name}}" {{if $fan.is_follow }}style="display: none"{{/if}}>关注</a>

                    <div class="fans-detail">
                        <a href="/home/index/p/{{$fan.user_id}}" class="fans-day" title="查看他的日记">{{$fan.diary_days}}个日子</a>
                        <a href=""/fans/index/p/{{$fan.user_id}}" class="fans-fans" title="查看他的粉丝">{{$fan.fans}}个粉丝</a>
                    </div>
                </li>
                {{/foreach}}
            </ul>
            <div class="paging-load">
                <div class="article-paging-box">
                    <ul class="article-paging-wrap clearfix">
                        {{if $page.pageNum != 1}}
                        <li class="article-paging-item"><a href=""/fans/index/page/{{$page.pageNum - 1}}" title="上一页">&lt上一页</a></li>
                        {{/if}}

                        {{assign var=pageSegment value="`$page.totalPageNum / 5`"|ceil}}
                        {{if $pageSegment < 2}}
                            {{section name=p start=1 loop=$page.totalPageNum + 1}}
                            <li class="article-paging-item {{if $page.pageNum == $smarty.section.p.index}}current{{/if}}"><a href=""/fans/index/page/{{$smarty.section.p.index}}" title="第{{$smarty.section.p.index}}页">{{$smarty.section.p.index}}</a></li>
                            {{/section}}
                        {{/if}}

                        {{if $pageSegment >= 2}}
                            {{if $page.pageNum <= 5}}
                                {{section name=p start=1 loop=6}}
                                <li class="article-paging-item {{if $page.pageNum == $smarty.section.p.index}}current{{/if}}"><a href="/fans/index/page/{{$smarty.section.p.index}}" title="第{{$smarty.section.p.index}}页">{{$smarty.section.p.index}}</a></li>
                                {{/section}}
                                <li class="article-paging-item">...</li>
                                <li class="article-paging-item"><a href="/fans/index/page/{{$page.totalPageNum}}" title="第{{$page.totalPageNum}}页">{{$page.totalPageNum}}</a></li>
                            {{elseif $page.pageNum + 5 > $page.totalPageNum}}
                                <li class="article-paging-item"><a href="/fans/index/page/1" title="第1页">1</a></li>
                                <li class="article-paging-item">...</li>

                                {{section name=p start="`$page.totalPageNum - 4`" loop="`$page.totalPageNum + 1`"}}
                                <li class="article-paging-item {{if $page.pageNum == $smarty.section.p.index}}current{{/if}}"><a href="/fans/index/page/{{$smarty.section.p.index}}" title="第{{$smarty.section.p.index}}页">{{$smarty.section.p.index}}</a></li>
                                {{/section}}
                            {{elseif $pageSegment >= 3}}
                                <li class="article-paging-item"><a href="/fans/index/page/1" title="第1页">1</a></li>
                                <li class="article-paging-item">...</li>

                                {{section name=p start="`$page.pageNum - 2`" loop="`$page.pageNum + 3`"}}
                                <li class="article-paging-item {{if $page.pageNum == $smarty.section.p.index}}current{{/if}}"><a href="/fans/index/page/{{$smarty.section.p.index}}" title="第{{$smarty.section.p.index}}页">{{$smarty.section.p.index}}</a></li>
                                {{/section}}

                                <li class="article-paging-item">...</li>
                                <li class="article-paging-item"><a href="/fans/index/page/{{$page.totalPageNum}}" title="第{{$page.totalPageNum}}页">{{$page.totalPageNum}}</a></li>
                            {{/if}}
                        {{/if}}
                        {{if $page.totalPageNum != 1 &&  $page.pageNum != $page.totalPageNum}}
                        <li class="article-paging-item"><a href="/fans/index/page/{{$page.pageNum - 1}}" title="下一页">下一页&gt</a></li>
                        {{/if}}
                    </ul>
                </div>
            </div>
        </section>
    </div>
    <div class="footer-load"></div>
    <script src="/statics/js/jquery-1.10.1.min.js"></script>
    <script src="/statics/js/temp-ajax-load.js"></script>
    <script src="/statics/js/common.js"></script>
</body>
</html>