<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>留言板--365每天记</title>
        <link rel="stylesheet" href="/statics/css/common.css">
        <!--[if lt IE 9]>
        <script src="/statics/js/html5shiv.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="header-load"></div>
        <div class="main">
            <div class="home-load"></div>
            <section class="leave-message-wrap">
                <form action="/leavingMsg/docreate" method="post">
                    <input type="hidden" name="follow_id" id="follow_id"/>
                    <input type="hidden" name="host_id" value="{{$user.user_id}}">
                    <div class="leave-message">
                        <textarea class="comment-text" name="content" id="" placeholder="写留言吧"></textarea>
                        <div class="comment-btn-wrap">
                            <button class="comment-btn" type="submit" title="留言">留 言</button>
                        </div>
                        <div class="leavingmsg-load">
                            <ul class="leavingmsg-detail">
                                {{foreach from=$leaving_msg_list item=msg}}
                                <li class="comment-item">
                                    <img class="comment-head" src="/statics/images/message_img_smallhead.jpg" alt="头像">
                                    <div class="comment-main">
                                        {{if $msg.follow_id != 0}}
                                        <div class="reply-quote">
                                            <span>{{$leaving_msg_associate[$msg['follow_id']]['content']}}</span><a href="#" class="reply-to-author" title="{{$msg.vistor_name}}">{{$msg.vistor_name}}</a>
                                        </div>
                                        {{/if}}
                                        <p class="comment-content"><a class="article-author" href="#" title="{{$msg.vistor_name}}">{{$msg.vistor_name}}:</a>{{$msg.content}}</p>
                                        <p class="comment-other">
                                            <time class="article-time">{{$msg.create_time|date_format:"%Y年%m月%d日 %H:%M"}}</time><a href="" class="reply" title="回复" alt ="{{$msg.leaving_msg_id}}">回复</a><a href="#" class="delete" title="删除" alt ="{{$msg.leaving_msg_id}}">删除</a>
                                        </p>
                                    </div>
                                </li>
                                {{/foreach}}
                            </ul>
                        </div>
                        <div class="paging-load">
                            {{include file="lib/paging.phtml" pageUrl="/leavingmsg/index/page/"}}
                        </div>
                    </div>
                </form>
            </section>
        </div>
        <div class="footer-load"></div>
        <script src="/statics/js/jquery-1.10.1.min.js"></script>
        <script src="/statics/js/temp-ajax-load.js"></script>
        <script src="/statics/js/common.js"></script>
    </body>
</html>