<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>绑定邮箱--365每天记</title>
    <link rel="stylesheet" href="/statics/css/common.css">
    <!--[if lt IE 9]>
    <script src="/statics/js/html5shiv.js"></script>
    <![endif]-->
</head>
<body>
    <div class="container-email">
        <!--header开始-->
        <header>
        <div class="header-email clearfix">
            <h1 class="logo-email">
                <a href="index.html" title="logo"><img src="/statics/images/header-logo.png" alt="365Logo"></a>
                <span class="logo-slogan bind-email">每日一张照片，记录分享生活</span>
            </h1>
        </div>
        </header>
        <!--header结束-->
        <!--main开始-->
        <div class="main-email clearfix line">
            <h2>欢迎使用365.com!<span>还有一步，立刻开始365之旅！</span></h2>
            <!--用户信息开始-->
            <div class="user-content">
                <div class="user-pic"><a href="#" title=""><img src="/statics/images/user-info-img.gif" width="91" height="91"></a></div>
                <div class="user-info">
                    <div class="user-info-name"><a href="#" title="CSI">CSI</a></div>
                    <div class="user-info-position">
                    <a href="#" title="北京">北京</a>
                    </div>
                </div>
            </div>
            <!--用户信息结束-->
            <!--默认邮箱开始-->
            <div class="default-email">
                <form>
                    <label>默认邮箱：<input type="text" placeholder="默认邮箱用于找回您的账号，请放心填写。"/></label>
                    <a href="javascript:;" title="确认并进入365DAYS" class="default-email-submit"></a>
                </form>
            </div>
            <!--默认邮箱结束-->
        </div>
        <!--main结束-->
        <div class="footer-load"></div>
    </div>
    <script src="/statics/js/jquery-1.10.1.min.js"></script>
    <script src="/statics/js/temp-ajax-load.js"></script>
</body>
</html>